export const skillsData = [
  {
    "id": 2,
    "title": "HTML5",
    "url": "https://html.com/",
    "image": require("./img/html.png"),
    "percent": 98,
  },
  {
    "id": 3,
    "title": "CSS",
    "url": "https://web.dev/learn/css/",
    "image": require("./img/css.png"),
    "percent": 42,
  },
  {
    "id": 1,
    "title": "JavaScript",
    "url": "https://www.javascript.com/",
    "image": require("./img/javascript.gif"),
    "percent": 80,
    
  },
  {
    "id": 17,
    "title": "Python",
    "url": "https://laravel.com/",
    "image": require("./img/python.gif"),
    "percent": 10,
  },
  {
    "id": 8,
    "title": "Node.js",
    "url": "https://nodejs.org/en/",
    "image": require("./img/nodejs.png"),
    "percent": 55,
  },
  {
    "id": 9,
    "title": "React",
    "url": "https://reactjs.org/",
    "image": require("./img/react.png"),
    "percent": 41,
  },
  {
    "id": 7,
    "title": "MongoDB",
    "url": "https://www.mongodb.com/",
    "image": require("./img/mongodb.png"),
    "percent": 93,
  },
  {
    "id": 4,
    "title": "MySQL",
    "url": "https://www.mysql.com/",
    "image": require("./img/Database-mysql.svg.png"),
    "percent": 34,
  },
 
  {
    "id": 6,
    "title": "PHP",
    "url": "https://www.php.net/",
    "image": require("./img/php-logo.png"),
    "percent": 27,
  },
  {
    "id": 10,
    "title": "Laravel",
    "url": "https://laravel.com/",
    "image": require("./img/laravel1.png"),
    "percent": 10,
  },
  {
    "id": 5,
    "title": "C#",
    "url": "https://docs.microsoft.com/en-us/dotnet/csharp/",
    "image": require("./img/csharp.png"),
    "percent": 97,
  },
  {
    "id": 11,
    "title": "Asp.net",
    "url": "https://laravel.com/",
    "image": require("./img/aspnet.png"),
    "percent": 10,
  },
  {
    "id": 12,
    "title": "Figma",
    "url": "https://laravel.com/",
    "image": require("./img/figma.png"),
    "percent": 10,
  },
  {
    "id": 13,
    "title": "Wordpress",
    "url": "https://laravel.com/",
    "image": require("./img/iwordpress.gif"),
    "percent": 10,
  },
  {
    "id": 14,
    "title": "Webflow",
    "url": "https://laravel.com/",
    "image": require("./img/webflow.png"),
    "percent": 10,
  },
  {
    "id": 15,
    "title": "Bootstrap",
    "url": "https://laravel.com/",
    "image": require("./img/bootstrap.png"),
    "percent": 10,
  },
  {
    "id": 16,
    "title": "Tailwind",
    "url": "https://laravel.com/",
    "image": require("./img/tailwindcss.png"),
    "percent": 10,
  },
  {
    "id": 18,
    "title": "AWS",
    "url": "https://laravel.com/",
    "image": require("./img/AWS.png"),
    "percent": 10,
  }
  ]